# Generated by Django 5.1.6 on 2025-04-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_str',
            field=models.TextField(blank=True),
        ),
    ]
