# Generated by Django 5.1.6 on 2025-04-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_html_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html_str',
        ),
    ]
