# Generated by Django 5.1.6 on 2025-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_html_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='html_uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='html_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
