# Generated by Django 5.1.6 on 2025-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_html_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('Thought', 'thought'), ('News', 'News'), ('Tweet', 'Tweet'), ('Instagram Post', 'Instagram Post'), ('General', 'General')], default='General', max_length=100, null=True),
        ),
    ]
