# Generated by Django 5.1.6 on 2025-04-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_catagory_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
