# Generated by Django 5.1.6 on 2025-04-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_category_post_category_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category_str',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Thought', 'thought'), ('News', 'News'), ('Tweet', 'Tweet'), ('Instagram Post', 'Instagram Post'), ('General', 'General')], default='General', max_length=100, null=True),
        ),
    ]
