# Generated by Django 5.1.6 on 2025-02-12 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='command_post',
            new_name='comment_post',
        ),
    ]
